apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonAnnotations:
  contact: support@path4cloud.com
  app.kubernetes.io/managed-by: kustomize

labels:
- includeSelectors: true #false if don't want to apply to selectors
  pairs:
    team: path4Cloud

nameSuffix: -prod
namePrefix: app1-

images:
- name: nginx # Will look for container with image name nginx
  newName: nginx
  newTag: "1.22"

namespace: prod

replicas:
- name: nginx-deploy
  count: 2
