apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: prod

resources:
- ../../base

components:
- ../../components/logging
- ../../components/scaling
- ../../components/hardening
