apiVersion: v1
kind: Service
metadata:
  name: web1-service
spec:
  selector:
    app: nginx-web
  ports:
  - protocol: TCP
    port: 8080 # Service (external) port
    targetPort: 80 # Container's internal port
  type: NodePort
