apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
  - name: stress
    image: progrium/stress
    args: [ "--cpu", "2", "--vm", "2", "--vm-bytes", "128M", "--timeout", "60s" ]
