apiVersion: v1
kind: Pod
metadata:
  name: web1
  labels:
    app: nginx-web
spec:
  containers:
  - name: web1
    image: amitaryan0010/path4cloud-web:latest
    ports:
    - containerPort: 80
  tolerations:
  - key: disk
    operator: Equal
    value: ssd
    effect: NoSchedule
