apiVersion: v1
kind: Pod
metadata:
  name: web-test
  labels:
    app: nginx-web
spec:
  containers:
  - name: web-test
    image: amitaryan0010/path4cloud-web:latest
    ports:
    - containerPort: 80
  nodeSelector:
    env: test
      # set this lable to any node before creating the pod
      # kubectl label nodes <node_name> env=test
