apiVersion: v1
kind: Pod
metadata:
  name: web-affinity
spec:
  containers:
  - name: web-affinity
    image: amitaryan0010/path4cloud-web:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - cloud
        # kubectl label nodes <node_name> env=cloud
