apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-pod
  labels:
    app: fluentd-logging
spec:
  selector:
    matchLabels:
      app: fluentd-logging
  template:
    metadata:
      labels:
        app: fluentd-logging
    spec:
      containers:
      - name: fluentd-logging
        image: quay.io/fluentd_elasticsearch/fluentd:v5.0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
