apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    envFrom:
    - configMapRef:
        name: mysql-cm

## kubectl exec -it mysql -- mysql -uroot -p (will ask for password, provide which has been set above)

## please allow some time for mysql initializing, we can check the password has ben set or not using:
# kubectl exec -it mysql -- env | grep -i mysql
