apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    envFrom:
    - configMapRef:
        name: mysql-cm

## kubectl exec -it mysql -- mysql -uroot -p (will ask for password, provide which has been set above)
