apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    envFrom:
    - secretRef:
        name: mysql-sec

## kubectl exec -it mysql -- mysql -uroot (will ask for password, provide which has been set above)
