apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
spec:
  containers:
  - name: logger
    image: busybox
    command: [ "/bin/sh", "-c" ]
    args: [ "while true; do echo $(date) Writing log entry >> /logs/test.log; sleep 5; done" ]
    volumeMounts:
    - mountPath: /logs
      name: log-volume
  volumes:
  - name: log-volume
    hostPath:
      path: /tmp/pod-logs
      type: DirectoryOrCreate
