apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

# Since no storageClassName, Kubernetes uses the “no storageClass” default behavior and binds automatically if capacity & access mode match.
