apiVersion: v1
kind: Pod
metadata:
  name: local-sc-pod
spec:
  containers:
  - name: logger
    image: busybox
    command: [ "/bin/sh", "-c" ]
    args: [ "while true; do echo $(date) Writing log entry >> /data/test.log; sleep 5; done" ]
    volumeMounts:
    - name: local-storage
      mountPath: /data
  volumes:
  - name: local-storage
    persistentVolumeClaim:
      claimName: local-sc-pvc
