apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-team-binding
subjects:
- kind: User
  name: developer-1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app-team
  apiGroup: rbac.authorization.k8s.io

# kubectl create rolebinding <name> --role=<role_name> --user=<user_name>
