# creating a api-pod-sa service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-pod-sa
  namespace: default
---
# creating a service token for api-pod-sa account
apiVersion: v1
kind: Secret
metadata:
  name: api-pod-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: api-pod-sa
type: kubernetes.io/service-account-token
---
# creating a api-pod with api-pod-sa mounted inside
apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  namespace: default
spec:
  serviceAccountName: api-pod-sa
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: sa-token
      mountPath: /var/run/secrets/my-sa
      readOnly: true
  volumes:
  - name: sa-token
    secret:
      secretName: api-pod-sa-token

#### Lets test the api request with mouted SA and Token
# kubectl exec -it api-pod -- sh

# now we are inside the pod, we can use curl command to authenticate the pod to the Kubernetes API using your custom ServiceAccount token.

# you can check the token:
# cat /var/run/secrets/my-sa/token  
# (if we describe the secret outside of pod, we can see same token is assigned here)

# curl --cacert /var/run/secrets/my-sa/ca.crt \
#     --header "Authorization: Bearer $(cat /var/run/secrets/my-sa/token)" \
#     https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api
