# create a new config for a new deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: with-ingress-content-2
data:
  index.html: |
    Hello, Welcome to Home Page, I am exposed as Cluster IP but you can access me via nginx ingress controller.
  about.html: |
    Please check the official document for more info.
  contact.html: |
    Subscribe ot our channel for more info and support.
---
# create a pod
apiVersion: v1
kind: Pod
metadata:
  name: ingress-webapp
  labels:
    app: webapp-ingress
spec:
  containers:
  - name: webapp-container
    image: nginx:latest
    volumeMounts:
    - name: webapp-volume
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
    - name: webapp-volume
      mountPath: /usr/share/nginx/html/about.html
      subPath: about.html
    - name: webapp-volume
      mountPath: /usr/share/nginx/html/contact.html
      subPath: contact.html
  volumes:
  - name: webapp-volume
    configMap:
      name: with-ingress-content-2
---
# create a service as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: web2-service
spec:
  selector:
    app: webapp-ingress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

## we will try to access this application using ingress Service and access these different pages

# create a defulat ingress if no hosts are matched then request will be redirected to this page
---
apiVersion: v1
kind: Pod
metadata:
  name: default-page-pod
  labels:
    app: default-page
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    configMap:
      name: default-page-html
---
apiVersion: v1
kind: Service
metadata:
  name: default-page-service
spec:
  selector:
    app: default-page
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-page-html
data:
  index.html: |
    This page is not defined yet, we are working on it, please come back..
