apiVersion: v1
kind: Pod
metadata:
  name: full-probe-demo
spec:
  initContainers:
  - name: init-message
    image: busybox
    command: [ "sh", "-c", "echo Init container running...; sleep 5; echo Init done!" ]
  containers:
  - name: demo-app
    image: python:3.9-slim
    ports:
    - containerPort: 8080
    command: [ "python", "-m", "http.server", "8080" ]
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  - name: health-toggle
    image: busybox
    command:
    - sh
    - -c
    - |
      echo "Waiting 30s then killing python..."
      sleep 30
      pkill python || true
      sleep 600
