apiVersion: v1
kind: Pod
metadata:
  name: readiness-demo
  labels:
    app: demo
spec:
  containers:
  - name: demo-app
    image: python:3.9
    ports:
    - containerPort: 8080
    command: [ "sh", "-c", "echo Hello > index.html && python -m http.server 8080" ]
    readinessProbe:
      httpGet:
        path: /index.html
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  ports:
  - port: 80
    targetPort: 8080

# get into the pod and manually kill the health check
# kubectl exec -it readiness-demo -- sh
# pkill -f python

# and then check the service, pod IP has been removed from service endpoint:
# kubectl get endpoints demo-service -o wide
