apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrd.path4cloud.examples.dev
spec:
  group: path4cloud.examples.dev
  versions:
  - name: v1beta
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: mycrd
    singular: mycrds
    kind: StartLearn
    shortNames:
    - sl
