apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-webhook
  template:
    metadata:
      labels:
        app: validation-webhook
    spec:
      containers:
      - name: webhook
        image: amitaryan0010/validation-webhook:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      volumes:
      - name: certs
        secret:
          secretName: validate-webhook-tls-certs

## Service
---

apiVersion: v1
kind: Service
metadata:
  name: validation-webhook-svc
spec:
  selector:
    app: validation-webhook
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
