apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-label-validate-validation
webhooks:
- name: pod-label-validate.webhook.path4cloud.com
  rules:
  - apiGroups: [ "" ]
    apiVersions: [ "v1" ]
    operations: [ "CREATE" ]
    resources: [ "pods" ]
  clientConfig:
    service:
      name: validation-webhook-svc
      namespace: default
      path: /
    caBundle: LS0tLS1CRUdJTiBD..... # add the real key from validate-ca-bundle.txt
  admissionReviewVersions: [ "v1" ]
  sideEffects: None
  failurePolicy: Fail
