apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
#kind: ValidatingWebhookConfiguration
metadata:
  name: "webhook-server-config"
webhooks:
- name: "webhook-server-config"
  admissionReviewVersions: [ "v1" ]
  sideEffects: None
  clientConfig:
    #url: "https:webhook_server_url.com"
    service:
      namespace: webhook-demo
      name: "webhook-server-svc"
      path: "/mutate" # Modify objects before persistence
      #path: "/validate"   # Reject or approve requests
      port: 8443
    caBundle: "afjweoijfwellwefwef....." # cat tls.crt | base64 | tr -d '\n' > ca-bundle.txt
  rules:
  - apiGroups: [ "" ]
    apiVersions: [ "v1" ]
    operations: [ "CREATE" ]
    resources: [ "pods" ]
    scope: "Namespaced"

# this webhook-server denies all request for pod to run as root in container if no SecurityContext is provided. If no value is set to runAsNonRoot, a default 
# value"true" is applied and the used id defaults to 1234

# allow to run containers as root if runAsNonRoot set explicitly to "false" in the securityContext
