apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      type: mutation-webhook
      app: dev
  template:
    metadata:
      labels:
        type: mutation-webhook
        app: dev
    spec:
      containers:
      - name: webhook
        image: amitaryan0010/mutation-webhook:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      volumes:
      - name: certs
        secret:
          secretName: mutate-webhook-tls-certs

## Service
---

apiVersion: v1
kind: Service
metadata:
  name: mutation-webhook-svc
spec:
  selector:
    type: mutation-webhook
    app: dev
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
