apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutation-webhook
  template:
    metadata:
      labels:
        app: mutation-webhook
    spec:
      containers:
      - name: webhook
        image: amitaryan0010/mutation-webhook:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: mutate-webhook-tls-certs

## Service
---

apiVersion: v1
kind: Service
metadata:
  name: mutation-webhook-svc
spec:
  selector:
    app: mutation-webhook
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
