apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app-m: mutation-webhook
  template:
    metadata:
      labels:
        app-m: mutation-webhook
    spec:
      containers:
      - name: webhook
        image: amitaryan0010/mutation-webhook:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: webhook-tls-certs

## Service
# already created with validation-webhook server deployment, will use the same service.
