apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-label-validation
webhooks:
- name: pod-label.webhook.company.com
  rules:
  - apiGroups: [ "" ]
    apiVersions: [ "v1" ]
    operations: [ "CREATE" ]
    resources: [ "pods" ]
  clientConfig:
    service:
      name: validation-webhook-svc
      namespace: default
      path: /
    caBundle: <BASE64_ENCODED_CA_CERT>
  admissionReviewVersions: [ "v1" ]
  sideEffects: None
  failurePolicy: Fail
