apiVersion: v1
kind: Pod
metadata:
  name: mutate-pod
# we don't have labels for this pod but it will be added by pod-label-mutate.webhook.path4cloud.com
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
