apiVersion: v1
kind: Pod
metadata:
  name: override-pod
  labels:
    app: override-pod
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsNonRoot: false
  containers:
  - name: busybox
    image: busybox
    command: [ :sh", "-c", "echo I am running as used $(id -u)" ]
