apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-app
  template:
    metadata:
      labels:
        app: vpa-app
    spec:
      containers:
      - name: my-vpa
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "200m"

# Expose it as a Service
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-svc
spec:
  selector:
    app: vpa-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
