apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: mysql-local
  hostPath:
    path: /mnt/mysql/pv0
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: mysql-local
  hostPath:
    path: /mnt/mysql/pv1
  persistentVolumeReclaimPolicy: Retain
