# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app # all values comes from values.yaml
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: myweb
      {{- if .Values.org_env }} # lable will be set only if its defined in values.yaml file
        org_env: {{ .Values.org_env }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        # with block examples
        resources:
        {{- with .Values.resources.requests }}
          requests:
            cpu: {{ .cpu }}
            memeory: {{ .memory}}
        {{- end }}
        # if inside a with block we need to set the root path from values.yaml which are not inside block then we can set as:
        # {{ $.Release.Name }}
        {{- with .Values.resources.limits }}
          limits:
            cpu: {{ .cpu }}
            memeory: {{ .memory}}
        {{- end }}

---
# expose service if set to true in values.yaml file
{{- if .Values.Service.exposed }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name}}-app
{{- end }}