apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-app
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            cpu: "50m"
            memory: "112Mi"
          limits:
            cpu: "250m"
            memory: "224Mi"
